//
//  TransferService.swift
//  Bluetooth-EEG
//
//  Created by AyoubHan on 13/07/2021.
//

import Foundation
import CoreBluetooth

struct TransferService {

    // MARK: - EEG Service
    
    // 128-bit UUIDs generated by the terminal command $uuidgen
    static let EEG = CBMutableService(type: CBUUID(string: "2713313B-5F1A-47FD-9438-DF4E109FC3C0"), primary: true)
    
    // MARK: - EEG characteristics

    static let EEGChannels = CBMutableCharacteristic(type: CBUUID(string: "16493CCD-6FC6-47DF-89EE-5272C7CCBC7A"), properties: .read, value: nil, permissions: .readable)
    static let magnetometer = CBMutableCharacteristic(type: CBUUID(string: "5D648B65-E4AD-4A40-A85F-52BBBE0975AE"), properties: .read, value: nil, permissions: .readable)
    static let accelerometer = CBMutableCharacteristic(type: CBUUID(string: "D94CC78A-78D0-47D9-B637-8548AAF8184B"), properties: .read, value: nil, permissions: .readable)
    static let gyroscope = CBMutableCharacteristic(type: CBUUID(string: "DB326D4E-FBAB-4220-9E82-5AF9D1502F8F"), properties: .read, value: nil, permissions: .readable)
}

