//
//  TransferService.swift
//  Bluetooth-EEG
//
//  Created by AyoubHan on 13/07/2021.
//

import Foundation
import CoreBluetooth

struct TransferService {

    // MARK: - EEG Service
    
    // 128-bit UUIDs generated by the terminal command $uuidgen
    static let ElectroEncephalogram = CBUUID(string: "2713313B-5F1A-47FD-9438-DF4E109FC3C0")
    
    // MARK: - EEG characteristics

    static let EEGChannels = CBUUID(string: "16493CCD-6FC6-47DF-89EE-5272C7CCBC7A")
    static let magnetometer = CBUUID(string: "5D648B65-E4AD-4A40-A85F-52BBBE0975AE")
    static let accelerometer = CBUUID(string: "D94CC78A-78D0-47D9-B637-8548AAF8184B")
    static let gyroscope = CBUUID(string: "DB326D4E-FBAB-4220-9E82-5AF9D1502F8F")
}

